/**
 * Essay Deep Intelligence Distillation Runner
 *
 * Runs the essay-deep-prompts.js through Claude to generate
 * distilled knowledge files for the Admissions SLM.
 *
 * Usage:
 *   node backend/distillation/distill-essays.js                    # Run all fixed prompts
 *   node backend/distillation/distill-essays.js --id=essay-ai-landscape-2026  # Run single prompt
 *   node backend/distillation/distill-essays.js --layer=E7         # Run one layer
 *   node backend/distillation/distill-essays.js --opus             # Use Opus (higher quality, 5x cost)
 *   node backend/distillation/distill-essays.js --dry-run          # Preview without running
 *
 * Output: backend/knowledge-base/distilled/essay-deep/
 *
 * Cost estimate (Sonnet): ~$2-3 for all 15 fixed prompts
 * Cost estimate (Opus): ~$10-15 for all 15 fixed prompts
 */

import Anthropic from '@anthropic-ai/sdk';
import { promises as fs } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import dotenv from 'dotenv';
import { essayDeepPrompts } from './essay-deep-prompts.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
dotenv.config({ path: join(__dirname, '..', '..', '.env') });

const OUTPUT_DIR = join(__dirname, '..', 'knowledge-base', 'distilled', 'essay-deep');

// Parse CLI args
const args = process.argv.slice(2);
const useOpus = args.includes('--opus');
const dryRun = args.includes('--dry-run');
const targetId = args.find(a => a.startsWith('--id='))?.split('=')[1];
const targetLayer = args.find(a => a.startsWith('--layer='))?.split('=')[1]?.toLowerCase();

const MODEL = useOpus ? 'claude-opus-4-6' : 'claude-sonnet-4-6';

const LAYER_MAP = {
  'e1': 'essay-diagnostic',
  'e2': 'essay-school-specific',
  'e3': 'essay-worked-examples',
  'e4': 'essay-edge-cases',
  'e5': 'essay-process',
  'e6': 'essay-ecosystem',
  'e7': 'essay-cutting-edge',
  'e8': 'essay-ao-voice',
};

async function distillPrompt(client, promptDef) {
  console.log(`\n  Distilling: ${promptDef.title}...`);
  console.log(`  ID: ${promptDef.id}`);

  if (promptDef.isTemplate) {
    console.log('  ⚠ Template prompt — use distill-essays-per-school.js for per-school generation');
    return null;
  }

  if (dryRun) {
    console.log(`  [DRY RUN] Would generate ~2000-5000 words`);
    console.log(`  Prompt preview: ${promptDef.prompt.substring(0, 200)}...`);
    return null;
  }

  const startTime = Date.now();

  const response = await client.messages.create({
    model: MODEL,
    max_tokens: 8000,
    temperature: 0.2, // Low temp for factual/strategic consistency
    messages: [{ role: 'user', content: promptDef.prompt }],
  });

  const text = response.content[0].text;
  const elapsed = ((Date.now() - startTime) / 1000).toFixed(1);

  // Save to markdown file
  const filename = `${promptDef.id}.md`;
  const filepath = join(OUTPUT_DIR, filename);

  const header = `# ${promptDef.title}\n\n` +
    `> Generated by Wayfinder Essay Deep Intelligence System\n` +
    `> Model: ${MODEL} | Date: ${new Date().toISOString().split('T')[0]}\n` +
    `> Layer: ${promptDef.layer} | Tokens: ${response.usage.output_tokens}\n\n---\n\n`;

  await fs.writeFile(filepath, header + text);

  console.log(`  ✓ Done in ${elapsed}s — ${response.usage.output_tokens} tokens`);
  console.log(`  → ${filepath}`);

  return {
    id: promptDef.id,
    tokens: response.usage.input_tokens + response.usage.output_tokens,
    outputTokens: response.usage.output_tokens,
    elapsed: parseFloat(elapsed),
    filepath,
  };
}

async function run() {
  console.log('===========================================');
  console.log('  Wayfinder Essay Deep Distillation');
  console.log(`  Model: ${MODEL}`);
  console.log(`  Mode: ${dryRun ? 'DRY RUN' : 'LIVE'}`);
  console.log('===========================================');

  // Filter prompts
  let prompts = essayDeepPrompts.filter(p => !p.isTemplate);

  if (targetId) {
    prompts = prompts.filter(p => p.id === targetId);
    if (prompts.length === 0) {
      console.error(`\nERROR: No prompt found with id "${targetId}"`);
      console.log('Available IDs:');
      essayDeepPrompts.forEach(p => console.log(`  - ${p.id}`));
      process.exit(1);
    }
  }

  if (targetLayer) {
    const layerPrefix = LAYER_MAP[targetLayer];
    if (layerPrefix) {
      prompts = prompts.filter(p => p.id.startsWith(layerPrefix) || p.id.includes(layerPrefix));
    } else {
      console.error(`\nERROR: Unknown layer "${targetLayer}". Available: ${Object.keys(LAYER_MAP).join(', ')}`);
      process.exit(1);
    }
  }

  console.log(`\n  Prompts to process: ${prompts.length}`);

  // Ensure output directory
  await fs.mkdir(OUTPUT_DIR, { recursive: true });

  // Check for existing files (skip if already generated)
  const existingFiles = new Set();
  try {
    const files = await fs.readdir(OUTPUT_DIR);
    files.forEach(f => existingFiles.add(f.replace('.md', '')));
  } catch { /* dir doesn't exist yet */ }

  const skippable = prompts.filter(p => existingFiles.has(p.id));
  if (skippable.length > 0 && !targetId) {
    console.log(`\n  Already distilled (will skip): ${skippable.map(p => p.id).join(', ')}`);
    console.log('  Use --id=<id> to force re-generation of a specific prompt');
    prompts = prompts.filter(p => !existingFiles.has(p.id));
    console.log(`  Remaining: ${prompts.length}`);
  }

  if (prompts.length === 0) {
    console.log('\n  Nothing to do! All prompts already distilled.');
    return;
  }

  const client = new Anthropic();
  const results = [];
  let totalTokens = 0;

  for (const prompt of prompts) {
    try {
      const result = await distillPrompt(client, prompt);
      if (result) {
        results.push(result);
        totalTokens += result.tokens;
      }
    } catch (err) {
      console.log(`  ✗ FAILED: ${prompt.id} — ${err.message}`);
      if (err.message.includes('rate_limit')) {
        console.log('  Waiting 30s for rate limit...');
        await new Promise(r => setTimeout(r, 30000));
      }
    }
  }

  // Summary
  console.log('\n===========================================');
  console.log('  DISTILLATION COMPLETE');
  console.log(`  Prompts processed: ${results.length}`);
  console.log(`  Total tokens: ${totalTokens.toLocaleString()}`);
  console.log(`  Total time: ${results.reduce((s, r) => s + r.elapsed, 0).toFixed(0)}s`);
  const costPerToken = useOpus ? 0.000075 : 0.000015;
  console.log(`  Estimated cost: ~$${(totalTokens * costPerToken).toFixed(2)}`);
  console.log(`\n  Output directory: ${OUTPUT_DIR}`);
  console.log('===========================================');
}

run().catch(console.error);
