/**
 * Internships Data Scraper
 *
 * Comprehensive curated dataset of well-known internship programs.
 * Covers all major fields and geographic regions.
 *
 * Future: Can be extended to pull from USAJobs API, LinkedIn Jobs API, etc.
 */

import { saveScrapedData, log, categorizeField, normalizeState, deduplicateByKey } from '../base-scraper.js';

const SCRAPER_NAME = 'internships';

// ────────────────────────────────────────────────────────────────────
// CURATED INTERNSHIP DATABASE
// ────────────────────────────────────────────────────────────────────

const INTERNSHIPS_DATA = [
  // ─── BIG TECH ────────────────────────────────────────────────────
  {
    title: 'Software Engineering Intern (STEP)',
    company: 'Google',
    location: { city: 'Mountain View', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-04-15',
    description: 'Google STEP Program for early-career engineers and underrepresented groups. Work on real Google infrastructure and products.',
    majors: ['Computer Science', 'Software Engineering', 'Data Science'],
    tags: ['FAANG', 'competitive', 'paid', 'tech'],
    url: 'https://careers.google.com/internships/',
    stipend: '$8,000/month',
    duration: '12 weeks'
  },
  {
    title: 'Explore Microsoft Internship',
    company: 'Microsoft',
    location: { city: 'Redmond', state: 'WA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-04-01',
    description: 'Microsoft Explore program for underrepresented groups and first-generation college students. Mentorship and project work across divisions.',
    majors: ['Computer Science', 'Data Science', 'Information Systems'],
    tags: ['FAANG', 'diversity', 'paid', 'mentorship'],
    url: 'https://careers.microsoft.com/students/internships',
    stipend: '$7,500/month',
    duration: '12 weeks'
  },
  {
    title: 'Software Development Engineer Intern',
    company: 'Amazon',
    location: { city: 'Seattle', state: 'WA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-03-30',
    description: 'Amazon internships across AWS, retail, and logistics. Fast-paced environment with real customer impact.',
    majors: ['Computer Science', 'Software Engineering'],
    tags: ['FAANG', 'competitive', 'paid'],
    url: 'https://www.amazon.jobs/internships',
    stipend: '$8,500/month',
    duration: '12 weeks'
  },
  {
    title: 'Meta University Program',
    company: 'Meta (Facebook)',
    location: { city: 'Menlo Park', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-04-10',
    description: 'Meta University for first-time interns and underrepresented groups. Intensive coding bootcamp plus internship.',
    majors: ['Computer Science', 'Data Science'],
    tags: ['FAANG', 'bootcamp', 'paid', 'mentorship'],
    url: 'https://www.metacareers.com/internships/',
    stipend: '$8,000/month',
    duration: '12 weeks'
  },
  {
    title: 'Internship Program',
    company: 'Apple',
    location: { city: 'Cupertino', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-03-31',
    description: 'Apple internships in software engineering, hardware design, and more. Access to cutting-edge technology and industry leaders.',
    majors: ['Computer Science', 'Electrical Engineering', 'Software Engineering'],
    tags: ['FAANG', 'paid', 'competitive'],
    url: 'https://www.apple.com/careers/internship/',
    stipend: '$8,500/month',
    duration: '12 weeks'
  },
  {
    title: 'GPU Computing Internship',
    company: 'NVIDIA',
    location: { city: 'Santa Clara', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-04-05',
    description: 'NVIDIA internships in CUDA development, AI/ML, graphics, and systems. Work on next-generation computing platforms.',
    majors: ['Computer Science', 'Electrical Engineering', 'Data Science'],
    tags: ['paid', 'hardware', 'AI'],
    url: 'https://www.nvidia.com/en-us/about-nvidia/careers/',
    stipend: '$9,000/month',
    duration: '12 weeks'
  },
  {
    title: 'Software Engineering Internship',
    company: 'Salesforce',
    location: { city: 'San Francisco', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-04-12',
    description: 'Salesforce Futureforce program for university students. Mentoring and real project work on enterprise software.',
    majors: ['Computer Science', 'Business IT', 'Software Engineering'],
    tags: ['paid', 'mentorship', 'enterprise'],
    url: 'https://www.salesforce.com/company/careers/university-recruiting/',
    stipend: '$7,800/month',
    duration: '12 weeks'
  },
  {
    title: 'Summer Internship Program',
    company: 'Intel',
    location: { city: 'Santa Clara', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-03-28',
    description: 'Intel internships in chip design, software development, and hardware engineering across all locations.',
    majors: ['Electrical Engineering', 'Computer Science', 'Physics'],
    tags: ['paid', 'hardware', 'competitive'],
    url: 'https://www.intel.com/content/www/us/en/careers/internships.html',
    stipend: '$8,200/month',
    duration: '12 weeks'
  },
  {
    title: 'Engineering Internship',
    company: 'Uber',
    location: { city: 'San Francisco', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-04-08',
    description: 'Uber internships in backend, frontend, infrastructure, and mobile. Impact millions of users worldwide.',
    majors: ['Computer Science', 'Software Engineering'],
    tags: ['paid', 'startup-culture', 'competitive'],
    url: 'https://www.uber.com/en-US/careers/list/?keywords=internship',
    stipend: '$8,100/month',
    duration: '12 weeks'
  },
  {
    title: 'Engineering Internship',
    company: 'Airbnb',
    location: { city: 'San Francisco', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-04-10',
    description: 'Airbnb engineering internships. Work on platform serving millions of travelers and hosts.',
    majors: ['Computer Science', 'Software Engineering', 'Data Science'],
    tags: ['paid', 'startup', 'competitive'],
    url: 'https://careers.airbnb.com/positions/?search=internship',
    stipend: '$8,000/month',
    duration: '12 weeks'
  },
  {
    title: 'Summer Engineering Internship',
    company: 'LinkedIn',
    location: { city: 'Sunnyvale', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-04-05',
    description: 'LinkedIn internships across engineering, product, and data. Work on the world\'s largest professional network.',
    majors: ['Computer Science', 'Data Science', 'Software Engineering'],
    tags: ['paid', 'competitive'],
    url: 'https://careers.linkedin.com/internships',
    stipend: '$8,300/month',
    duration: '12 weeks'
  },

  // ─── FINANCE ────────────────────────────────────────────────────
  {
    title: 'Summer Analyst Program',
    company: 'Goldman Sachs',
    location: { city: 'New York', state: 'NY' },
    type: 'summer',
    paid: true,
    field: 'Business',
    deadline: '2026-02-28',
    description: 'Goldman Sachs prestigious summer analyst program. Investment banking, trading, and operations tracks.',
    majors: ['Finance', 'Economics', 'Business', 'Mathematics'],
    tags: ['finance', 'competitive', 'paid', 'banking'],
    url: 'https://www.goldmansachs.com/careers/students/programs/americas/summer-analyst.html',
    stipend: '$13,000/month',
    duration: '10 weeks'
  },
  {
    title: 'Summer Analyst Program',
    company: 'JP Morgan Chase',
    location: { city: 'New York', state: 'NY' },
    type: 'summer',
    paid: true,
    field: 'Business',
    deadline: '2026-03-01',
    description: 'JPMorgan summer analyst internship. Work in investment banking, equities, fixed income, or operations.',
    majors: ['Finance', 'Business', 'Economics', 'Engineering'],
    tags: ['finance', 'banking', 'paid', 'competitive'],
    url: 'https://careers.jpmchase.com/us/en/students/programs',
    stipend: '$12,500/month',
    duration: '10 weeks'
  },
  {
    title: 'Summer Program',
    company: 'Morgan Stanley',
    location: { city: 'New York', state: 'NY' },
    type: 'summer',
    paid: true,
    field: 'Business',
    deadline: '2026-02-25',
    description: 'Morgan Stanley summer internship program. Investment banking, sales & trading, research, and wealth management.',
    majors: ['Finance', 'Business', 'Economics', 'Mathematics'],
    tags: ['finance', 'banking', 'paid', 'competitive'],
    url: 'https://www.morganstanley.com/careers/opportunities-for-students',
    stipend: '$13,200/month',
    duration: '10 weeks'
  },
  {
    title: 'Summer Analyst Program',
    company: 'Citigroup',
    location: { city: 'New York', state: 'NY' },
    type: 'summer',
    paid: true,
    field: 'Business',
    deadline: '2026-03-05',
    description: 'Citi summer analyst program. Opportunities in investment banking, markets, treasury, and operations.',
    majors: ['Finance', 'Business', 'Economics'],
    tags: ['finance', 'banking', 'paid'],
    url: 'https://www.citigroup.com/citi/careers/students/',
    stipend: '$12,000/month',
    duration: '10 weeks'
  },
  {
    title: 'Internship Program',
    company: 'BlackRock',
    location: { city: 'New York', state: 'NY' },
    type: 'summer',
    paid: true,
    field: 'Business',
    deadline: '2026-03-10',
    description: 'BlackRock internship in investment management, trading, technology, and operations.',
    majors: ['Finance', 'Business', 'Computer Science', 'Mathematics'],
    tags: ['finance', 'investing', 'paid'],
    url: 'https://blackrock.wd5.myworkdayobs.com/careers',
    stipend: '$12,000/month',
    duration: '10 weeks'
  },
  {
    title: 'Summer Internship',
    company: 'Fidelity Investments',
    location: { city: 'Boston', state: 'MA' },
    type: 'summer',
    paid: true,
    field: 'Business',
    deadline: '2026-03-15',
    description: 'Fidelity internships across portfolio management, trading, technology, and business operations.',
    majors: ['Finance', 'Computer Science', 'Business', 'Mathematics'],
    tags: ['finance', 'investing', 'paid'],
    url: 'https://jobs.fidelity.com/careers',
    stipend: '$11,500/month',
    duration: '10 weeks'
  },
  {
    title: 'Consulting Internship',
    company: 'McKinsey & Company',
    location: { city: 'New York', state: 'NY' },
    type: 'summer',
    paid: true,
    field: 'Business',
    deadline: '2026-02-20',
    description: 'McKinsey summer internship for undergraduates. Consulting experience with top Fortune 500 clients.',
    majors: ['Business', 'Economics', 'Engineering', 'Mathematics'],
    tags: ['consulting', 'paid', 'competitive'],
    url: 'https://www.mckinsey.com/careers/search-jobs?interests=students',
    stipend: '$11,000/month',
    duration: '12 weeks'
  },
  {
    title: 'Consulting Internship',
    company: 'Boston Consulting Group',
    location: { city: 'Boston', state: 'MA' },
    type: 'summer',
    paid: true,
    field: 'Business',
    deadline: '2026-02-22',
    description: 'BCG internship program. Work on strategic problems for leading global companies.',
    majors: ['Business', 'Engineering', 'Economics', 'Mathematics'],
    tags: ['consulting', 'paid', 'competitive'],
    url: 'https://www.bcg.com/careers/internships',
    stipend: '$10,800/month',
    duration: '12 weeks'
  },
  {
    title: 'Consulting Internship',
    company: 'Bain & Company',
    location: { city: 'Boston', state: 'MA' },
    type: 'summer',
    paid: true,
    field: 'Business',
    deadline: '2026-02-25',
    description: 'Bain summer internship for undergraduate students. Client-facing consulting experience.',
    majors: ['Business', 'Engineering', 'Economics', 'Mathematics'],
    tags: ['consulting', 'paid', 'competitive'],
    url: 'https://www.bain.com/careers/our-internships/',
    stipend: '$10,500/month',
    duration: '12 weeks'
  },
  {
    title: 'Audit/Advisory Internship',
    company: 'Deloitte',
    location: { city: 'New York', state: 'NY' },
    type: 'summer',
    paid: true,
    field: 'Business',
    deadline: '2026-03-20',
    description: 'Deloitte internships in audit, consulting, advisory, and tax across multiple locations.',
    majors: ['Accounting', 'Business', 'Finance', 'Computer Science'],
    tags: ['accounting', 'consulting', 'paid'],
    url: 'https://www.deloitte.com/us/en/careers/students.html',
    stipend: '$10,000/month',
    duration: '10 weeks'
  },
  {
    title: 'Internship Program',
    company: 'PwC',
    location: { city: 'New York', state: 'NY' },
    type: 'summer',
    paid: true,
    field: 'Business',
    deadline: '2026-03-18',
    description: 'PwC internships in assurance, tax, advisory, and deals across US locations.',
    majors: ['Accounting', 'Business', 'Finance', 'Computer Science'],
    tags: ['accounting', 'consulting', 'paid'],
    url: 'https://www.pwc.com/us/en/careers/students.html',
    stipend: '$9,800/month',
    duration: '10 weeks'
  },
  {
    title: 'Internship Program',
    company: 'EY (Ernst & Young)',
    location: { city: 'New York', state: 'NY' },
    type: 'summer',
    paid: true,
    field: 'Business',
    deadline: '2026-03-22',
    description: 'EY internships in assurance, tax, consulting, and transactions.',
    majors: ['Accounting', 'Business', 'Finance', 'Computer Science'],
    tags: ['accounting', 'consulting', 'paid'],
    url: 'https://careers.ey.com/students',
    stipend: '$9,600/month',
    duration: '10 weeks'
  },
  {
    title: 'Internship Program',
    company: 'KPMG',
    location: { city: 'New York', state: 'NY' },
    type: 'summer',
    paid: true,
    field: 'Business',
    deadline: '2026-03-25',
    description: 'KPMG internships in audit, tax, advisory, and IT solutions.',
    majors: ['Accounting', 'Business', 'Finance', 'Computer Science'],
    tags: ['accounting', 'consulting', 'paid'],
    url: 'https://home.kpmg/us/en/home/careers/students.html',
    stipend: '$9,400/month',
    duration: '10 weeks'
  },

  // ─── GOVERNMENT & NONPROFIT ──────────────────────────────────
  {
    title: 'Internship Program',
    company: 'NASA',
    location: { city: 'Various', state: 'MD' },
    type: 'summer',
    paid: true,
    field: 'Science',
    deadline: '2026-03-30',
    description: 'NASA OSSI internships across all centers. Contribute to space exploration and scientific research.',
    majors: ['Engineering', 'Physics', 'Computer Science', 'Aerospace Engineering'],
    tags: ['government', 'paid', 'research'],
    url: 'https://intern.nasa.gov/',
    stipend: '$8,000/month',
    duration: '10-12 weeks'
  },
  {
    title: 'Intramural Research Program',
    company: 'NIH (National Institutes of Health)',
    location: { city: 'Bethesda', state: 'MD' },
    type: 'summer',
    paid: true,
    field: 'Healthcare',
    deadline: '2026-04-15',
    description: 'NIH IRTA program. Work with leading biomedical researchers on cutting-edge health discoveries.',
    majors: ['Biology', 'Chemistry', 'Biochemistry', 'Biomedical Sciences'],
    tags: ['government', 'research', 'paid'],
    url: 'https://www.training.nih.gov/programs/irta',
    stipend: '$7,500/month',
    duration: '10 weeks'
  },
  {
    title: 'Summer Internship',
    company: 'EPA (Environmental Protection Agency)',
    location: { city: 'Washington', state: 'DC' },
    type: 'summer',
    paid: true,
    field: 'Science',
    deadline: '2026-03-15',
    description: 'EPA internships in environmental science, policy, and engineering. Protect human health and the environment.',
    majors: ['Environmental Science', 'Engineering', 'Chemistry', 'Policy'],
    tags: ['government', 'paid', 'environment'],
    url: 'https://www.epa.gov/careers/student-opportunities',
    stipend: '$7,000/month',
    duration: '10 weeks'
  },
  {
    title: 'Internship Program',
    company: 'CDC (Centers for Disease Control)',
    location: { city: 'Atlanta', state: 'GA' },
    type: 'summer',
    paid: true,
    field: 'Healthcare',
    deadline: '2026-03-20',
    description: 'CDC internships in epidemiology, public health, and disease prevention.',
    majors: ['Public Health', 'Biology', 'Epidemiology', 'Medicine'],
    tags: ['government', 'health', 'paid'],
    url: 'https://www.cdc.gov/careers/students.html',
    stipend: '$7,200/month',
    duration: '10 weeks'
  },
  {
    title: 'Internship',
    company: 'Smithsonian Institution',
    location: { city: 'Washington', state: 'DC' },
    type: 'summer',
    paid: false,
    field: 'Arts & Media',
    deadline: '2026-04-01',
    description: 'Smithsonian internships across museums. Experience world-class collections and research.',
    majors: ['Art History', 'Museum Studies', 'History', 'Anthropology'],
    tags: ['nonprofit', 'unpaid', 'arts'],
    url: 'https://www.si.edu/internships',
    stipend: null,
    duration: '8-10 weeks'
  },
  {
    title: 'Summer Internship',
    company: 'United Nations',
    location: { city: 'New York', state: 'NY' },
    type: 'summer',
    paid: false,
    field: 'Law & Government',
    deadline: '2026-02-15',
    description: 'UN internships across agencies and programs. Work on global humanitarian and development issues.',
    majors: ['International Relations', 'Political Science', 'Economics', 'Development Studies'],
    tags: ['nonprofit', 'international', 'competitive'],
    url: 'https://careers.un.org/lbw/home.aspx?viewtype=IM',
    stipend: null,
    duration: '8 weeks'
  },
  {
    title: 'Internship Program',
    company: 'World Bank',
    location: { city: 'Washington', state: 'DC' },
    type: 'summer',
    paid: true,
    field: 'Business',
    deadline: '2026-03-01',
    description: 'World Bank internships in development economics, finance, and policy.',
    majors: ['Economics', 'Finance', 'Development Studies', 'Business'],
    tags: ['nonprofit', 'paid', 'international'],
    url: 'https://www.worldbank.org/en/about/careers',
    stipend: '$6,000/month',
    duration: '12 weeks'
  },
  {
    title: 'Internship Program',
    company: 'State Department',
    location: { city: 'Washington', state: 'DC' },
    type: 'summer',
    paid: false,
    field: 'Law & Government',
    deadline: '2026-03-10',
    description: 'US State Department internships in diplomacy, policy, and foreign affairs.',
    majors: ['International Relations', 'Political Science', 'Economics', 'Languages'],
    tags: ['government', 'competitive', 'unpaid'],
    url: 'https://careers.state.gov/students/',
    stipend: null,
    duration: '12 weeks'
  },
  {
    title: 'Summer Internship',
    company: 'World Wildlife Fund',
    location: { city: 'Washington', state: 'DC' },
    type: 'summer',
    paid: false,
    field: 'Science',
    deadline: '2026-03-25',
    description: 'WWF internships in conservation, policy, and sustainability.',
    majors: ['Environmental Science', 'Biology', 'Policy', 'Business'],
    tags: ['nonprofit', 'environment', 'unpaid'],
    url: 'https://www.worldwildlife.org/careers',
    stipend: null,
    duration: '10 weeks'
  },

  // ─── HEALTHCARE & BIOTECH ────────────────────────────────────
  {
    title: 'Summer Internship',
    company: 'Pfizer',
    location: { city: 'New York', state: 'NY' },
    type: 'summer',
    paid: true,
    field: 'Healthcare',
    deadline: '2026-03-30',
    description: 'Pfizer internships in research, development, manufacturing, and commercial operations.',
    majors: ['Chemistry', 'Biology', 'Biochemistry', 'Pharmacy', 'Engineering'],
    tags: ['pharma', 'paid', 'research'],
    url: 'https://www.pfizer.com/careers/students',
    stipend: '$10,000/month',
    duration: '12 weeks'
  },
  {
    title: 'Internship Program',
    company: 'Genentech',
    location: { city: 'South San Francisco', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Healthcare',
    deadline: '2026-03-28',
    description: 'Genentech internships in research, development, and engineering for biotech innovations.',
    majors: ['Biology', 'Chemistry', 'Biochemistry', 'Engineering', 'Computer Science'],
    tags: ['biotech', 'paid', 'research'],
    url: 'https://www.gene.com/careers/students',
    stipend: '$11,000/month',
    duration: '12 weeks'
  },
  {
    title: 'Summer Internship',
    company: 'Mayo Clinic',
    location: { city: 'Rochester', state: 'MN' },
    type: 'summer',
    paid: true,
    field: 'Healthcare',
    deadline: '2026-04-05',
    description: 'Mayo Clinic internships in research, clinical care, and health administration.',
    majors: ['Medicine', 'Biology', 'Chemistry', 'Health Administration'],
    tags: ['healthcare', 'paid', 'research'],
    url: 'https://www.mayo.edu/careers/students',
    stipend: '$8,500/month',
    duration: '10 weeks'
  },
  {
    title: 'Summer Internship',
    company: 'Johnson & Johnson',
    location: { city: 'New Brunswick', state: 'NJ' },
    type: 'summer',
    paid: true,
    field: 'Healthcare',
    deadline: '2026-03-25',
    description: 'J&J internships across pharmaceuticals, consumer health, and medical devices.',
    majors: ['Chemistry', 'Engineering', 'Business', 'Biology'],
    tags: ['pharma', 'paid', 'diversified'],
    url: 'https://www.jnj.com/careers/students',
    stipend: '$9,500/month',
    duration: '12 weeks'
  },
  {
    title: 'Internship',
    company: 'Merck',
    location: { city: 'Kenilworth', state: 'NJ' },
    type: 'summer',
    paid: true,
    field: 'Healthcare',
    deadline: '2026-03-28',
    description: 'Merck internships in pharmaceutical research, manufacturing, and development.',
    majors: ['Chemistry', 'Biology', 'Biochemistry', 'Engineering'],
    tags: ['pharma', 'paid', 'research'],
    url: 'https://www.merck.com/careers/students/',
    stipend: '$9,800/month',
    duration: '12 weeks'
  },
  {
    title: 'Internship Program',
    company: 'AbbVie',
    location: { city: 'North Chicago', state: 'IL' },
    type: 'summer',
    paid: true,
    field: 'Healthcare',
    deadline: '2026-03-30',
    description: 'AbbVie internships in research, manufacturing, and commercial operations.',
    majors: ['Chemistry', 'Biology', 'Engineering', 'Business'],
    tags: ['pharma', 'paid'],
    url: 'https://www.abbvie.com/careers',
    stipend: '$9,200/month',
    duration: '12 weeks'
  },

  // ─── ENGINEERING ────────────────────────────────────────────
  {
    title: 'Engineering Internship',
    company: 'Boeing',
    location: { city: 'Seattle', state: 'WA' },
    type: 'summer',
    paid: true,
    field: 'Engineering',
    deadline: '2026-03-15',
    description: 'Boeing internships in aerospace engineering, software, systems, and manufacturing.',
    majors: ['Aerospace Engineering', 'Mechanical Engineering', 'Electrical Engineering', 'Computer Science'],
    tags: ['aerospace', 'paid', 'engineering'],
    url: 'https://www.boeing.com/careers',
    stipend: '$8,500/month',
    duration: '12 weeks'
  },
  {
    title: 'Internship Program',
    company: 'Lockheed Martin',
    location: { city: 'Fort Worth', state: 'TX' },
    type: 'summer',
    paid: true,
    field: 'Engineering',
    deadline: '2026-03-20',
    description: 'Lockheed Martin internships in engineering, IT, and business across multiple facilities.',
    majors: ['Aerospace Engineering', 'Electrical Engineering', 'Computer Science', 'Physics'],
    tags: ['aerospace', 'defense', 'paid'],
    url: 'https://www.lockheedmartin.com/en-us/careers/find-jobs.html',
    stipend: '$8,200/month',
    duration: '12 weeks'
  },
  {
    title: 'Engineering Internship',
    company: 'SpaceX',
    location: { city: 'Hawthorne', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Engineering',
    deadline: '2026-02-28',
    description: 'SpaceX engineering internships in propulsion, structures, avionics, and software for rocket development.',
    majors: ['Aerospace Engineering', 'Mechanical Engineering', 'Electrical Engineering', 'Computer Science'],
    tags: ['aerospace', 'startup', 'paid', 'competitive'],
    url: 'https://www.spacex.com/careers',
    stipend: '$9,500/month',
    duration: '12 weeks'
  },
  {
    title: 'Summer Internship',
    company: 'Tesla',
    location: { city: 'Palo Alto', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Engineering',
    deadline: '2026-03-31',
    description: 'Tesla internships in mechanical engineering, electrical engineering, and software across design, manufacturing, and operations.',
    majors: ['Mechanical Engineering', 'Electrical Engineering', 'Computer Science'],
    tags: ['automotive', 'paid', 'competitive'],
    url: 'https://www.tesla.com/careers',
    stipend: '$8,800/month',
    duration: '12 weeks'
  },
  {
    title: 'Internship Program',
    company: 'General Electric',
    location: { city: 'Boston', state: 'MA' },
    type: 'summer',
    paid: true,
    field: 'Engineering',
    deadline: '2026-03-10',
    description: 'GE internships in power, renewable energy, aviation, and healthcare equipment engineering.',
    majors: ['Electrical Engineering', 'Mechanical Engineering', 'Chemical Engineering'],
    tags: ['engineering', 'diversified', 'paid'],
    url: 'https://www.ge.com/careers',
    stipend: '$8,000/month',
    duration: '12 weeks'
  },
  {
    title: 'Engineering Internship',
    company: 'Caterpillar',
    location: { city: 'Peoria', state: 'IL' },
    type: 'summer',
    paid: true,
    field: 'Engineering',
    deadline: '2026-03-25',
    description: 'Caterpillar internships in mechanical, electrical, and software engineering for heavy equipment.',
    majors: ['Mechanical Engineering', 'Electrical Engineering', 'Computer Science'],
    tags: ['engineering', 'paid'],
    url: 'https://www.caterpillar.com/careers',
    stipend: '$7,800/month',
    duration: '12 weeks'
  },
  {
    title: 'Summer Internship',
    company: 'Raytheon Technologies',
    location: { city: 'Waltham', state: 'MA' },
    type: 'summer',
    paid: true,
    field: 'Engineering',
    deadline: '2026-03-20',
    description: 'Raytheon internships in defense, aerospace, and cybersecurity engineering.',
    majors: ['Electrical Engineering', 'Aerospace Engineering', 'Computer Science'],
    tags: ['defense', 'aerospace', 'paid'],
    url: 'https://www.rtx.com/careers',
    stipend: '$8,300/month',
    duration: '12 weeks'
  },

  // ─── MEDIA & ENTERTAINMENT ──────────────────────────────────
  {
    title: 'Internship Program',
    company: 'Disney',
    location: { city: 'Burbank', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Arts & Media',
    deadline: '2026-03-15',
    description: 'Disney internships across creative, technology, and business divisions. Work in animation, visual effects, software, and more.',
    majors: ['Computer Science', 'Animation', 'Art', 'Business', 'Engineering'],
    tags: ['media', 'entertainment', 'paid'],
    url: 'https://www.waltdisneystudios.com/careers/',
    stipend: '$7,500/month',
    duration: '12 weeks'
  },
  {
    title: 'Internship Program',
    company: 'NBCUniversal',
    location: { city: 'Los Angeles', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Arts & Media',
    deadline: '2026-03-20',
    description: 'NBCUniversal internships in production, post-production, and digital media.',
    majors: ['Media Studies', 'Film', 'Business', 'Computer Science'],
    tags: ['media', 'entertainment', 'paid'],
    url: 'https://www.nbcuniversal.com/careers',
    stipend: '$7,000/month',
    duration: '12 weeks'
  },
  {
    title: 'Internship',
    company: 'Warner Bros',
    location: { city: 'Burbank', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Arts & Media',
    deadline: '2026-03-10',
    description: 'Warner Bros internships in film, television, animation, and digital media production.',
    majors: ['Film Studies', 'Animation', 'Business', 'Computer Science'],
    tags: ['media', 'entertainment', 'paid'],
    url: 'https://www.warnerbros.com/careers',
    stipend: '$7,200/month',
    duration: '12 weeks'
  },
  {
    title: 'Summer Internship',
    company: 'Spotify',
    location: { city: 'New York', state: 'NY' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-04-05',
    description: 'Spotify engineering and product internships. Work on the world\'s leading music streaming platform.',
    majors: ['Computer Science', 'Software Engineering', 'Data Science'],
    tags: ['tech', 'music', 'paid'],
    url: 'https://www.spotifyjobs.com/',
    stipend: '$8,000/month',
    duration: '12 weeks'
  },
  {
    title: 'Internship Program',
    company: 'Netflix',
    location: { city: 'Los Gatos', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-03-28',
    description: 'Netflix internships in engineering, product, and data science. Impact millions of viewers globally.',
    majors: ['Computer Science', 'Data Science', 'Engineering'],
    tags: ['tech', 'streaming', 'paid', 'competitive'],
    url: 'https://jobs.netflix.com/',
    stipend: '$8,500/month',
    duration: '12 weeks'
  },

  // ─── RESEARCH & NSF REU ──────────────────────────────────────
  {
    title: 'Research Experience for Undergraduates',
    company: 'NSF (Computer Science)',
    location: { city: 'Arlington', state: 'VA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-02-15',
    description: 'NSF REU in computer science. Research opportunities at universities across the US.',
    majors: ['Computer Science', 'Software Engineering', 'Data Science'],
    tags: ['research', 'paid', 'academic'],
    url: 'https://www.nsf.gov/funding/programs/',
    stipend: '$6,000/month',
    duration: '10 weeks'
  },
  {
    title: 'Research Experience for Undergraduates',
    company: 'NSF (Biology)',
    location: { city: 'Arlington', state: 'VA' },
    type: 'summer',
    paid: true,
    field: 'Science',
    deadline: '2026-02-15',
    description: 'NSF REU in biological sciences. Work with faculty mentors on research projects.',
    majors: ['Biology', 'Biochemistry', 'Molecular Biology'],
    tags: ['research', 'paid', 'academic'],
    url: 'https://www.nsf.gov/funding/programs/',
    stipend: '$6,000/month',
    duration: '10 weeks'
  },
  {
    title: 'Research Experience for Undergraduates',
    company: 'NSF (Chemistry)',
    location: { city: 'Arlington', state: 'VA' },
    type: 'summer',
    paid: true,
    field: 'Science',
    deadline: '2026-02-15',
    description: 'NSF REU in chemistry and materials science.',
    majors: ['Chemistry', 'Chemical Engineering', 'Materials Science'],
    tags: ['research', 'paid', 'academic'],
    url: 'https://www.nsf.gov/funding/programs/',
    stipend: '$6,000/month',
    duration: '10 weeks'
  },
  {
    title: 'Research Experience for Undergraduates',
    company: 'NSF (Physics)',
    location: { city: 'Arlington', state: 'VA' },
    type: 'summer',
    paid: true,
    field: 'Science',
    deadline: '2026-02-15',
    description: 'NSF REU in physics and astronomy.',
    majors: ['Physics', 'Astronomy', 'Engineering Physics'],
    tags: ['research', 'paid', 'academic'],
    url: 'https://www.nsf.gov/funding/programs/',
    stipend: '$6,000/month',
    duration: '10 weeks'
  },
  {
    title: 'Research Experience for Undergraduates',
    company: 'NSF (Environmental Science)',
    location: { city: 'Arlington', state: 'VA' },
    type: 'summer',
    paid: true,
    field: 'Science',
    deadline: '2026-02-15',
    description: 'NSF REU in environmental science and ecology.',
    majors: ['Environmental Science', 'Biology', 'Geology'],
    tags: ['research', 'paid', 'academic'],
    url: 'https://www.nsf.gov/funding/programs/',
    stipend: '$6,000/month',
    duration: '10 weeks'
  },
  {
    title: 'Research Experience for Undergraduates',
    company: 'NSF (Mathematics)',
    location: { city: 'Arlington', state: 'VA' },
    type: 'summer',
    paid: true,
    field: 'Science',
    deadline: '2026-02-15',
    description: 'NSF REU in mathematics and statistics.',
    majors: ['Mathematics', 'Statistics', 'Applied Mathematics'],
    tags: ['research', 'paid', 'academic'],
    url: 'https://www.nsf.gov/funding/programs/',
    stipend: '$6,000/month',
    duration: '10 weeks'
  },
  {
    title: 'Research Experience for Undergraduates',
    company: 'NSF (Engineering)',
    location: { city: 'Arlington', state: 'VA' },
    type: 'summer',
    paid: true,
    field: 'Engineering',
    deadline: '2026-02-15',
    description: 'NSF REU in mechanical, electrical, and civil engineering.',
    majors: ['Mechanical Engineering', 'Electrical Engineering', 'Civil Engineering'],
    tags: ['research', 'paid', 'academic'],
    url: 'https://www.nsf.gov/funding/programs/',
    stipend: '$6,000/month',
    duration: '10 weeks'
  },
  {
    title: 'Summer Research Program',
    company: 'DOE SULI (Department of Energy)',
    location: { city: 'Washington', state: 'DC' },
    type: 'summer',
    paid: true,
    field: 'Science',
    deadline: '2026-02-01',
    description: 'DOE SULI program. Research at national laboratories in clean energy and physics.',
    majors: ['Engineering', 'Physics', 'Chemistry', 'Computer Science'],
    tags: ['government', 'research', 'paid'],
    url: 'https://science.osti.gov/wdts/suli',
    stipend: '$7,000/month',
    duration: '10 weeks'
  },
  {
    title: 'Summer Internship',
    company: 'Argonne National Laboratory',
    location: { city: 'Lemont', state: 'IL' },
    type: 'summer',
    paid: true,
    field: 'Science',
    deadline: '2026-02-15',
    description: 'Argonne internships in physics, chemistry, and advanced computing research.',
    majors: ['Physics', 'Chemistry', 'Computer Science', 'Engineering'],
    tags: ['research', 'paid', 'government'],
    url: 'https://www.anl.gov/',
    stipend: '$6,800/month',
    duration: '10 weeks'
  },
  {
    title: 'Summer Internship',
    company: 'Fermilab',
    location: { city: 'Batavia', state: 'IL' },
    type: 'summer',
    paid: true,
    field: 'Science',
    deadline: '2026-02-20',
    description: 'Fermilab internships in particle physics and accelerator science.',
    majors: ['Physics', 'Computer Science', 'Engineering'],
    tags: ['research', 'paid', 'government'],
    url: 'https://www.fnal.gov/',
    stipend: '$6,500/month',
    duration: '10 weeks'
  },
  {
    title: 'Summer Student Program',
    company: 'CERN',
    location: { city: 'Geneva', state: 'Switzerland' },
    type: 'summer',
    paid: true,
    field: 'Science',
    deadline: '2026-01-31',
    description: 'CERN summer program. Collaborate with physicists on international particle physics research.',
    majors: ['Physics', 'Computer Science', 'Engineering'],
    tags: ['research', 'paid', 'international', 'competitive'],
    url: 'https://careers.cern/',
    stipend: '$5,500/month',
    duration: '13 weeks'
  },

  // ─── PRE-COLLEGE PROGRAMS ────────────────────────────────────
  {
    title: 'Summer Engineering Program (High School)',
    company: 'Carnegie Mellon University',
    location: { city: 'Pittsburgh', state: 'PA' },
    type: 'summer',
    paid: false,
    field: 'Engineering',
    deadline: '2026-04-01',
    description: 'Pre-college summer engineering program for high school students interested in engineering.',
    majors: ['Pre-college', 'STEM'],
    tags: ['precollege', 'stem', 'unpaid'],
    url: 'https://www.cmu.edu/precollege/',
    stipend: null,
    duration: '2-4 weeks'
  },
  {
    title: 'Summer Science Program',
    company: 'MIT Summer Research Program',
    location: { city: 'Cambridge', state: 'MA' },
    type: 'summer',
    paid: false,
    field: 'Science',
    deadline: '2026-03-15',
    description: 'MIT research program for promising high school students in STEM.',
    majors: ['Pre-college', 'STEM'],
    tags: ['precollege', 'research', 'competitive'],
    url: 'https://www.mit.edu/',
    stipend: null,
    duration: '3 weeks'
  },
  {
    title: 'Tech Summer Camp',
    company: 'Stanford Pre-Collegiate Program',
    location: { city: 'Palo Alto', state: 'CA' },
    type: 'summer',
    paid: false,
    field: 'Technology',
    deadline: '2026-04-10',
    description: 'Stanford summer camp for high school students in computer science and technology.',
    majors: ['Pre-college', 'Computer Science'],
    tags: ['precollege', 'tech', 'unpaid'],
    url: 'https://online.stanford.edu/programs',
    stipend: null,
    duration: '2-4 weeks'
  },

  // ─── STARTUP & GROWTH-STAGE ──────────────────────────────────
  {
    title: 'Engineering Internship',
    company: 'Stripe',
    location: { city: 'San Francisco', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-04-15',
    description: 'Stripe internship. Work on payments infrastructure and developer tools.',
    majors: ['Computer Science', 'Software Engineering'],
    tags: ['fintech', 'paid', 'startup'],
    url: 'https://stripe.com/jobs',
    stipend: '$8,500/month',
    duration: '12 weeks'
  },
  {
    title: 'Engineering Internship',
    company: 'Canva',
    location: { city: 'Sydney', state: 'Australia' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-04-01',
    description: 'Canva design engineering internship. Work on the world\'s most-used design platform.',
    majors: ['Computer Science', 'Software Engineering', 'Design'],
    tags: ['paid', 'design-tech', 'startup'],
    url: 'https://www.canva.com/careers/',
    stipend: '$8,000/month',
    duration: '12 weeks'
  },
  {
    title: 'Software Internship',
    company: 'Figma',
    location: { city: 'San Francisco', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-04-10',
    description: 'Figma internship in frontend, backend, or design infrastructure.',
    majors: ['Computer Science', 'Software Engineering'],
    tags: ['paid', 'design-tech', 'startup'],
    url: 'https://www.figma.com/careers/',
    stipend: '$8,200/month',
    duration: '12 weeks'
  },
  {
    title: 'Engineering Internship',
    company: 'Notion',
    location: { city: 'San Francisco', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-04-12',
    description: 'Notion engineering internship. Help millions organize their lives and work.',
    majors: ['Computer Science', 'Software Engineering'],
    tags: ['paid', 'productivity', 'startup'],
    url: 'https://www.notion.so/careers/',
    stipend: '$8,000/month',
    duration: '12 weeks'
  },
  {
    title: 'Engineering Internship',
    company: 'Slack',
    location: { city: 'San Francisco', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-04-08',
    description: 'Slack engineering internship. Work on communication platform used by millions.',
    majors: ['Computer Science', 'Software Engineering'],
    tags: ['paid', 'communication', 'startup'],
    url: 'https://slack.com/careers',
    stipend: '$8,300/month',
    duration: '12 weeks'
  },
  {
    title: 'Product & Engineering Internship',
    company: 'Discord',
    location: { city: 'San Francisco', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-04-05',
    description: 'Discord internship in engineering or product. Build the platform powering communities.',
    majors: ['Computer Science', 'Software Engineering'],
    tags: ['paid', 'gaming', 'startup'],
    url: 'https://discord.com/careers',
    stipend: '$8,000/month',
    duration: '12 weeks'
  },

  // ─── ADDITIONAL TECH & FINANCE ───────────────────────────────
  {
    title: 'Summer Internship',
    company: 'Dropbox',
    location: { city: 'San Francisco', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-04-02',
    description: 'Dropbox engineering internship. Work on file storage and sync infrastructure.',
    majors: ['Computer Science', 'Software Engineering'],
    tags: ['paid', 'tech'],
    url: 'https://www.dropbox.com/jobs',
    stipend: '$8,100/month',
    duration: '12 weeks'
  },
  {
    title: 'Internship Program',
    company: 'Snapchat',
    location: { city: 'Los Angeles', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-04-01',
    description: 'Snapchat internship in engineering, product, or design.',
    majors: ['Computer Science', 'Software Engineering', 'Design'],
    tags: ['paid', 'social-media'],
    url: 'https://snap.com/careers',
    stipend: '$8,200/month',
    duration: '12 weeks'
  },
  {
    title: 'Engineering Internship',
    company: 'Twitter',
    location: { city: 'San Francisco', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-03-25',
    description: 'Twitter (now X) engineering internship. Work on core platform infrastructure.',
    majors: ['Computer Science', 'Software Engineering'],
    tags: ['paid', 'social-media'],
    url: 'https://x.com/careers',
    stipend: '$8,000/month',
    duration: '12 weeks'
  },
  {
    title: 'Investment Banking Internship',
    company: 'Evercore',
    location: { city: 'New York', state: 'NY' },
    type: 'summer',
    paid: true,
    field: 'Business',
    deadline: '2026-02-20',
    description: 'Evercore investment banking summer analyst program.',
    majors: ['Finance', 'Business', 'Economics'],
    tags: ['finance', 'banking', 'paid'],
    url: 'https://www.evercoreisi.com/careers',
    stipend: '$12,000/month',
    duration: '10 weeks'
  },
  {
    title: 'Internship Program',
    company: 'Bank of America',
    location: { city: 'Charlotte', state: 'NC' },
    type: 'summer',
    paid: true,
    field: 'Business',
    deadline: '2026-03-05',
    description: 'Bank of America internships across investment banking, wealth management, and operations.',
    majors: ['Finance', 'Business', 'Economics', 'Computer Science'],
    tags: ['banking', 'paid'],
    url: 'https://careers.bankofamerica.com',
    stipend: '$11,000/month',
    duration: '10 weeks'
  },
  {
    title: 'Summer Analyst Program',
    company: 'Barclays',
    location: { city: 'New York', state: 'NY' },
    type: 'summer',
    paid: true,
    field: 'Business',
    deadline: '2026-02-28',
    description: 'Barclays summer analyst in investment banking and capital markets.',
    majors: ['Finance', 'Economics', 'Business'],
    tags: ['banking', 'paid', 'international'],
    url: 'https://www.barclays.com/careers',
    stipend: '$12,500/month',
    duration: '10 weeks'
  },
  {
    title: 'Summer Intern Program',
    company: 'Wells Fargo',
    location: { city: 'Charlotte', state: 'NC' },
    type: 'summer',
    paid: true,
    field: 'Business',
    deadline: '2026-03-10',
    description: 'Wells Fargo internship in banking, wealth management, and corporate operations.',
    majors: ['Finance', 'Business', 'Economics'],
    tags: ['banking', 'paid'],
    url: 'https://www.wellsfargo.com/careers',
    stipend: '$10,500/month',
    duration: '10 weeks'
  },
  {
    title: 'Technology Internship',
    company: 'Square/Cash App',
    location: { city: 'San Francisco', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-04-05',
    description: 'Square engineering internship. Work on fintech infrastructure and mobile apps.',
    majors: ['Computer Science', 'Software Engineering'],
    tags: ['fintech', 'paid'],
    url: 'https://squareup.com/careers',
    stipend: '$8,400/month',
    duration: '12 weeks'
  },
  {
    title: 'Engineering Internship',
    company: 'Robinhood',
    location: { city: 'Menlo Park', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-04-03',
    description: 'Robinhood internship in backend, frontend, or mobile for fintech platform.',
    majors: ['Computer Science', 'Software Engineering', 'Data Science'],
    tags: ['fintech', 'paid', 'startup'],
    url: 'https://robinhood.com/careers',
    stipend: '$8,300/month',
    duration: '12 weeks'
  },
  {
    title: 'Data Science Internship',
    company: 'Airbnb',
    location: { city: 'San Francisco', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-04-01',
    description: 'Airbnb data science internship. Analyze global marketplace data and build ML models.',
    majors: ['Data Science', 'Statistics', 'Computer Science'],
    tags: ['data', 'paid', 'competitive'],
    url: 'https://careers.airbnb.com/positions/?search=internship',
    stipend: '$8,200/month',
    duration: '12 weeks'
  },

  // ─── ADDITIONAL ENGINEERING ─────────────────────────────────
  {
    title: 'Engineering Internship',
    company: 'Qualcomm',
    location: { city: 'San Diego', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Engineering',
    deadline: '2026-03-28',
    description: 'Qualcomm internship in chip design, software, and systems for mobile communications.',
    majors: ['Electrical Engineering', 'Computer Science', 'Physics'],
    tags: ['semiconductor', 'paid'],
    url: 'https://www.qualcomm.com/careers',
    stipend: '$8,500/month',
    duration: '12 weeks'
  },
  {
    title: 'Summer Internship',
    company: 'Broadcom',
    location: { city: 'San Jose', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Engineering',
    deadline: '2026-03-30',
    description: 'Broadcom internship in semiconductor and infrastructure software engineering.',
    majors: ['Electrical Engineering', 'Computer Science'],
    tags: ['semiconductor', 'paid'],
    url: 'https://www.broadcom.com/careers',
    stipend: '$8,300/month',
    duration: '12 weeks'
  },
  {
    title: 'Engineering Internship',
    company: 'Cisco',
    location: { city: 'San Jose', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-04-08',
    description: 'Cisco internship in networking, software, and security engineering.',
    majors: ['Computer Science', 'Electrical Engineering'],
    tags: ['networking', 'paid'],
    url: 'https://jobs.cisco.com/',
    stipend: '$8,000/month',
    duration: '12 weeks'
  },
  {
    title: 'Engineering Internship',
    company: 'Juniper Networks',
    location: { city: 'Sunnyvale', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-04-05',
    description: 'Juniper internship in routing, switching, security, and cloud infrastructure.',
    majors: ['Computer Science', 'Electrical Engineering'],
    tags: ['networking', 'paid'],
    url: 'https://www.juniper.net/careers/',
    stipend: '$7,900/month',
    duration: '12 weeks'
  },

  // ─── ADDITIONAL HEALTHCARE & GOVERNMENT ──────────────────
  {
    title: 'Internship Program',
    company: 'FDA',
    location: { city: 'Silver Spring', state: 'MD' },
    type: 'summer',
    paid: false,
    field: 'Healthcare',
    deadline: '2026-03-15',
    description: 'FDA internships in drug approval, food safety, and medical devices.',
    majors: ['Biology', 'Chemistry', 'Health Administration', 'Regulatory Affairs'],
    tags: ['government', 'healthcare', 'unpaid'],
    url: 'https://www.fda.gov/jobs/careers',
    stipend: null,
    duration: '10 weeks'
  },
  {
    title: 'USGS Summer Internship',
    company: 'United States Geological Survey',
    location: { city: 'Reston', state: 'VA' },
    type: 'summer',
    paid: true,
    field: 'Science',
    deadline: '2026-03-20',
    description: 'USGS internships in geology, geophysics, hydrology, and earth science.',
    majors: ['Geology', 'Environmental Science', 'Physics'],
    tags: ['government', 'paid', 'research'],
    url: 'https://www.usgs.gov/careers',
    stipend: '$6,500/month',
    duration: '10 weeks'
  },
  {
    title: 'Internship Program',
    company: 'Department of Defense',
    location: { city: 'Washington', state: 'DC' },
    type: 'summer',
    paid: true,
    field: 'Engineering',
    deadline: '2026-03-01',
    description: 'DoD internships in defense, engineering, and intelligence.',
    majors: ['Engineering', 'Computer Science', 'Physics'],
    tags: ['government', 'paid', 'security-clearance'],
    stipend: '$7,500/month',
    duration: '10 weeks',
    url: 'https://www.dod.gov/careers'
  },
  {
    title: 'Summer Internship',
    company: 'National Science Foundation',
    location: { city: 'Arlington', state: 'VA' },
    type: 'summer',
    paid: true,
    field: 'Science',
    deadline: '2026-03-10',
    description: 'NSF internships supporting STEM research and education programs.',
    majors: ['Science', 'Engineering', 'Education'],
    tags: ['government', 'research', 'paid'],
    url: 'https://www.nsf.gov/careers/',
    stipend: '$6,800/month',
    duration: '10 weeks'
  },

  // ─── ENERGY & UTILITIES ──────────────────────────────────────
  {
    title: 'Engineering Internship',
    company: 'NextEra Energy',
    location: { city: 'Juno Beach', state: 'FL' },
    type: 'summer',
    paid: true,
    field: 'Engineering',
    deadline: '2026-03-25',
    description: 'NextEra internship in renewable energy, nuclear, and operations.',
    majors: ['Electrical Engineering', 'Mechanical Engineering'],
    tags: ['energy', 'paid'],
    url: 'https://www.nexteraenergy.com/careers',
    stipend: '$7,800/month',
    duration: '12 weeks'
  },
  {
    title: 'Summer Internship',
    company: 'Duke Energy',
    location: { city: 'Charlotte', state: 'NC' },
    type: 'summer',
    paid: true,
    field: 'Engineering',
    deadline: '2026-03-30',
    description: 'Duke Energy internships in power generation, transmission, and distribution.',
    majors: ['Electrical Engineering', 'Mechanical Engineering'],
    tags: ['energy', 'paid'],
    url: 'https://www.dukeenergy.com/careers',
    stipend: '$7,600/month',
    duration: '12 weeks'
  },
  {
    title: 'Internship Program',
    company: 'Southern Company',
    location: { city: 'Atlanta', state: 'GA' },
    type: 'summer',
    paid: true,
    field: 'Engineering',
    deadline: '2026-03-28',
    description: 'Southern Company internship in power systems and renewable energy.',
    majors: ['Electrical Engineering', 'Mechanical Engineering'],
    tags: ['energy', 'paid'],
    url: 'https://www.southerncompany.com/careers',
    stipend: '$7,500/month',
    duration: '12 weeks'
  },

  // ─── AUTOMOTIVE ────────────────────────────────────────────────
  {
    title: 'Engineering Internship',
    company: 'Ford',
    location: { city: 'Dearborn', state: 'MI' },
    type: 'summer',
    paid: true,
    field: 'Engineering',
    deadline: '2026-03-20',
    description: 'Ford engineering internship in vehicle design, powertrains, and autonomy.',
    majors: ['Mechanical Engineering', 'Electrical Engineering', 'Software Engineering'],
    tags: ['automotive', 'paid'],
    url: 'https://www.ford.com/careers',
    stipend: '$8,000/month',
    duration: '12 weeks'
  },
  {
    title: 'Engineering Internship',
    company: 'General Motors',
    location: { city: 'Detroit', state: 'MI' },
    type: 'summer',
    paid: true,
    field: 'Engineering',
    deadline: '2026-03-22',
    description: 'GM internship in EV development, autonomous vehicles, and manufacturing.',
    majors: ['Mechanical Engineering', 'Electrical Engineering', 'Software Engineering'],
    tags: ['automotive', 'paid'],
    url: 'https://www.gm.com/careers',
    stipend: '$8,200/month',
    duration: '12 weeks'
  },
  {
    title: 'Engineering Internship',
    company: 'Toyota',
    location: { city: 'Georgetown', state: 'KY' },
    type: 'summer',
    paid: true,
    field: 'Engineering',
    deadline: '2026-03-25',
    description: 'Toyota internship in hybrid and electric vehicle development.',
    majors: ['Mechanical Engineering', 'Electrical Engineering'],
    tags: ['automotive', 'paid'],
    url: 'https://www.toyota.com/careers',
    stipend: '$7,900/month',
    duration: '12 weeks'
  },
  {
    title: 'Engineering Internship',
    company: 'Volkswagen',
    location: { city: 'Chattanooga', state: 'TN' },
    type: 'summer',
    paid: true,
    field: 'Engineering',
    deadline: '2026-03-28',
    description: 'Volkswagen engineering internship in EV technology and manufacturing.',
    majors: ['Mechanical Engineering', 'Electrical Engineering'],
    tags: ['automotive', 'paid'],
    url: 'https://www.volkswagen.com/careers',
    stipend: '$8,100/month',
    duration: '12 weeks'
  },
  {
    title: 'Engineering Internship',
    company: 'Honda',
    location: { city: 'Columbus', state: 'OH' },
    type: 'summer',
    paid: true,
    field: 'Engineering',
    deadline: '2026-03-25',
    description: 'Honda internship in vehicle engineering and manufacturing technology.',
    majors: ['Mechanical Engineering', 'Electrical Engineering'],
    tags: ['automotive', 'paid'],
    url: 'https://www.honda.com/careers',
    stipend: '$7,700/month',
    duration: '12 weeks'
  },

  // ─── ADDITIONAL TECH COMPANIES ──────────────────────────────
  {
    title: 'Software Engineering Internship',
    company: 'Zoom',
    location: { city: 'San Jose', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-04-08',
    description: 'Zoom engineering internship in video communication infrastructure.',
    majors: ['Computer Science', 'Software Engineering'],
    tags: ['tech', 'paid', 'communication'],
    url: 'https://zoom.us/careers',
    stipend: '$8,000/month',
    duration: '12 weeks'
  },
  {
    title: 'Engineering Internship',
    company: 'Twilio',
    location: { city: 'San Francisco', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-04-10',
    description: 'Twilio internship in communication APIs and infrastructure.',
    majors: ['Computer Science', 'Software Engineering'],
    tags: ['tech', 'paid', 'api'],
    url: 'https://www.twilio.com/careers',
    stipend: '$8,100/month',
    duration: '12 weeks'
  },
  {
    title: 'Engineering Internship',
    company: 'Datadog',
    location: { city: 'New York', state: 'NY' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-04-12',
    description: 'Datadog internship in cloud monitoring and observability.',
    majors: ['Computer Science', 'Software Engineering', 'Data Science'],
    tags: ['tech', 'paid', 'monitoring'],
    url: 'https://www.datadoghq.com/careers',
    stipend: '$8,200/month',
    duration: '12 weeks'
  },
  {
    title: 'Engineering Internship',
    company: 'HashiCorp',
    location: { city: 'San Francisco', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-04-05',
    description: 'HashiCorp internship in infrastructure automation software.',
    majors: ['Computer Science', 'Software Engineering'],
    tags: ['tech', 'paid', 'infrastructure'],
    url: 'https://www.hashicorp.com/careers',
    stipend: '$8,000/month',
    duration: '12 weeks'
  },
  {
    title: 'Software Engineering Internship',
    company: 'Okta',
    location: { city: 'San Francisco', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-04-10',
    description: 'Okta internship in identity and access management.',
    majors: ['Computer Science', 'Software Engineering', 'Security'],
    tags: ['tech', 'security', 'paid'],
    url: 'https://www.okta.com/careers',
    stipend: '$8,100/month',
    duration: '12 weeks'
  },
  {
    title: 'Engineering Internship',
    company: 'Atlassian',
    location: { city: 'San Francisco', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-04-08',
    description: 'Atlassian internship in collaboration and DevOps software.',
    majors: ['Computer Science', 'Software Engineering'],
    tags: ['tech', 'paid', 'devops'],
    url: 'https://www.atlassian.com/company/careers',
    stipend: '$8,000/month',
    duration: '12 weeks'
  },
  {
    title: 'Software Engineering Internship',
    company: 'Crowdstrike',
    location: { city: 'Sunnyvale', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-04-05',
    description: 'CrowdStrike internship in cybersecurity and endpoint protection.',
    majors: ['Computer Science', 'Software Engineering', 'Cybersecurity'],
    tags: ['tech', 'security', 'paid'],
    url: 'https://www.crowdstrike.com/careers',
    stipend: '$8,300/month',
    duration: '12 weeks'
  },
  {
    title: 'Engineering Internship',
    company: 'Palo Alto Networks',
    location: { city: 'Santa Clara', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-04-03',
    description: 'Palo Alto internship in cybersecurity platforms.',
    majors: ['Computer Science', 'Software Engineering', 'Cybersecurity'],
    tags: ['tech', 'security', 'paid'],
    url: 'https://careers.paloaltonetworks.com',
    stipend: '$8,200/month',
    duration: '12 weeks'
  },
  {
    title: 'Machine Learning Internship',
    company: 'OpenAI',
    location: { city: 'San Francisco', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-04-01',
    description: 'OpenAI internship in machine learning and AI research.',
    majors: ['Computer Science', 'Mathematics', 'Physics'],
    tags: ['ai', 'research', 'paid', 'competitive'],
    url: 'https://openai.com/careers',
    stipend: '$9,000/month',
    duration: '12 weeks'
  },
  {
    title: 'Research Internship',
    company: 'DeepMind',
    location: { city: 'London', state: 'UK' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-03-15',
    description: 'DeepMind internship in artificial intelligence research.',
    majors: ['Computer Science', 'Mathematics', 'Physics'],
    tags: ['ai', 'research', 'paid', 'competitive'],
    url: 'https://deepmind.com/careers',
    stipend: '$8,500/month',
    duration: '12 weeks'
  },

  // ─── FINANCE (ADDITIONAL) ──────────────────────────────────
  {
    title: 'Trading Internship',
    company: 'Citadel',
    location: { city: 'Chicago', state: 'IL' },
    type: 'summer',
    paid: true,
    field: 'Business',
    deadline: '2026-02-10',
    description: 'Citadel trading and technology internship. Work at elite hedge fund.',
    majors: ['Finance', 'Computer Science', 'Mathematics', 'Physics'],
    tags: ['finance', 'trading', 'paid', 'competitive'],
    url: 'https://careers.citadel.com',
    stipend: '$15,000/month',
    duration: '10 weeks'
  },
  {
    title: 'Trading Internship',
    company: 'Jump Trading',
    location: { city: 'Chicago', state: 'IL' },
    type: 'summer',
    paid: true,
    field: 'Business',
    deadline: '2026-02-15',
    description: 'Jump Trading internship in quantitative trading and tech.',
    majors: ['Computer Science', 'Mathematics', 'Physics', 'Finance'],
    tags: ['finance', 'trading', 'paid', 'competitive'],
    url: 'https://jumptrading.com/careers',
    stipend: '$14,000/month',
    duration: '10 weeks'
  },
  {
    title: 'Summer Analyst Program',
    company: 'Lazard',
    location: { city: 'New York', state: 'NY' },
    type: 'summer',
    paid: true,
    field: 'Business',
    deadline: '2026-03-05',
    description: 'Lazard investment banking summer analyst.',
    majors: ['Finance', 'Business', 'Economics'],
    tags: ['banking', 'paid'],
    url: 'https://www.lazard.com/careers',
    stipend: '$12,200/month',
    duration: '10 weeks'
  },
  {
    title: 'Summer Analyst',
    company: 'Rothschild',
    location: { city: 'New York', state: 'NY' },
    type: 'summer',
    paid: true,
    field: 'Business',
    deadline: '2026-03-08',
    description: 'Rothschild investment banking internship.',
    majors: ['Finance', 'Business', 'Economics'],
    tags: ['banking', 'paid'],
    url: 'https://www.rothschild.com/careers',
    stipend: '$12,000/month',
    duration: '10 weeks'
  },
  {
    title: 'Summer Analyst Program',
    company: 'Apollo Global Management',
    location: { city: 'New York', state: 'NY' },
    type: 'summer',
    paid: true,
    field: 'Business',
    deadline: '2026-03-12',
    description: 'Apollo internship in private equity and credit.',
    majors: ['Finance', 'Business', 'Economics'],
    tags: ['finance', 'private-equity', 'paid'],
    url: 'https://www.apolloglobal.com/careers',
    stipend: '$12,500/month',
    duration: '10 weeks'
  },
  {
    title: 'Private Equity Internship',
    company: 'KKR',
    location: { city: 'New York', state: 'NY' },
    type: 'summer',
    paid: true,
    field: 'Business',
    deadline: '2026-02-25',
    description: 'KKR private equity summer internship.',
    majors: ['Finance', 'Business', 'Economics'],
    tags: ['finance', 'private-equity', 'paid', 'competitive'],
    url: 'https://careers.kkr.com',
    stipend: '$13,000/month',
    duration: '10 weeks'
  },
  {
    title: 'Private Equity Internship',
    company: 'Carlyle Group',
    location: { city: 'Washington', state: 'DC' },
    type: 'summer',
    paid: true,
    field: 'Business',
    deadline: '2026-03-01',
    description: 'Carlyle Group private equity summer internship.',
    majors: ['Finance', 'Business', 'Economics'],
    tags: ['finance', 'private-equity', 'paid'],
    url: 'https://www.carlyle.com/careers',
    stipend: '$12,800/month',
    duration: '10 weeks'
  },
  {
    title: 'Venture Capital Internship',
    company: 'Sequoia Capital',
    location: { city: 'Menlo Park', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Business',
    deadline: '2026-03-15',
    description: 'Sequoia Capital venture capital internship.',
    majors: ['Business', 'Computer Science', 'Finance'],
    tags: ['venture-capital', 'paid', 'startup'],
    url: 'https://www.sequoiacap.com/careers',
    stipend: '$10,000/month',
    duration: '12 weeks'
  },
  {
    title: 'Venture Capital Internship',
    company: 'Andreessen Horowitz (a16z)',
    location: { city: 'Menlo Park', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Business',
    deadline: '2026-03-20',
    description: 'Andreessen Horowitz VC internship.',
    majors: ['Business', 'Computer Science', 'Engineering'],
    tags: ['venture-capital', 'paid', 'startup'],
    url: 'https://a16z.com/careers',
    stipend: '$10,200/month',
    duration: '12 weeks'
  },

  // ─── ADDITIONAL CONSULTING ─────────────────────────────────
  {
    title: 'Consulting Internship',
    company: 'Strategy&',
    location: { city: 'New York', state: 'NY' },
    type: 'summer',
    paid: true,
    field: 'Business',
    deadline: '2026-03-01',
    description: 'Strategy& (PwC subsidiary) consulting internship.',
    majors: ['Business', 'Engineering', 'Economics'],
    tags: ['consulting', 'paid'],
    url: 'https://www.strategyand.pwc.com/careers',
    stipend: '$10,500/month',
    duration: '12 weeks'
  },
  {
    title: 'Consulting Internship',
    company: 'Accenture',
    location: { city: 'New York', state: 'NY' },
    type: 'summer',
    paid: true,
    field: 'Business',
    deadline: '2026-03-10',
    description: 'Accenture consulting and technology internship.',
    majors: ['Business', 'Computer Science', 'Engineering'],
    tags: ['consulting', 'paid'],
    url: 'https://www.accenture.com/careers',
    stipend: '$10,000/month',
    duration: '12 weeks'
  },
  {
    title: 'Consulting Internship',
    company: 'Capgemini',
    location: { city: 'New York', state: 'NY' },
    type: 'summer',
    paid: true,
    field: 'Business',
    deadline: '2026-03-12',
    description: 'Capgemini consulting and digital transformation internship.',
    majors: ['Business', 'Computer Science', 'Engineering'],
    tags: ['consulting', 'paid'],
    url: 'https://www.capgemini.com/careers',
    stipend: '$9,800/month',
    duration: '12 weeks'
  },
  {
    title: 'Consulting Internship',
    company: 'IBM Consulting',
    location: { city: 'Armonk', state: 'NY' },
    type: 'summer',
    paid: true,
    field: 'Business',
    deadline: '2026-03-15',
    description: 'IBM consulting and technology services internship.',
    majors: ['Computer Science', 'Business', 'Engineering'],
    tags: ['consulting', 'paid', 'tech'],
    url: 'https://www.ibm.com/careers',
    stipend: '$9,600/month',
    duration: '12 weeks'
  },

  // ─── HEALTHCARE (ADDITIONAL) ────────────────────────────────
  {
    title: 'Research Internship',
    company: 'Gilead Sciences',
    location: { city: 'Foster City', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Healthcare',
    deadline: '2026-03-25',
    description: 'Gilead research internship in virology and drug development.',
    majors: ['Chemistry', 'Biology', 'Biochemistry'],
    tags: ['pharma', 'research', 'paid'],
    url: 'https://www.gilead.com/careers',
    stipend: '$10,500/month',
    duration: '12 weeks'
  },
  {
    title: 'Engineering Internship',
    company: 'Medtronic',
    location: { city: 'Minneapolis', state: 'MN' },
    type: 'summer',
    paid: true,
    field: 'Engineering',
    deadline: '2026-03-20',
    description: 'Medtronic medical device engineering internship.',
    majors: ['Biomedical Engineering', 'Electrical Engineering', 'Mechanical Engineering'],
    tags: ['medical-devices', 'paid'],
    url: 'https://careers.medtronic.com',
    stipend: '$9,000/month',
    duration: '12 weeks'
  },
  {
    title: 'Research Internship',
    company: 'Novartis',
    location: { city: 'Cambridge', state: 'MA' },
    type: 'summer',
    paid: true,
    field: 'Healthcare',
    deadline: '2026-03-28',
    description: 'Novartis pharmaceutical research internship.',
    majors: ['Chemistry', 'Biology', 'Biochemistry'],
    tags: ['pharma', 'research', 'paid'],
    url: 'https://www.novartis.com/careers',
    stipend: '$10,200/month',
    duration: '12 weeks'
  },

  // ─── CONSUMER GOODS & RETAIL ────────────────────────────────
  {
    title: 'Summer Internship',
    company: 'Procter & Gamble',
    location: { city: 'Cincinnati', state: 'OH' },
    type: 'summer',
    paid: true,
    field: 'Business',
    deadline: '2026-03-20',
    description: 'P&G internship in marketing, supply chain, and operations.',
    majors: ['Business', 'Engineering', 'Chemistry'],
    tags: ['consumer-goods', 'paid'],
    url: 'https://www.pg.com/en_US/careers/',
    stipend: '$8,500/month',
    duration: '12 weeks'
  },
  {
    title: 'Internship Program',
    company: 'Coca-Cola',
    location: { city: 'Atlanta', state: 'GA' },
    type: 'summer',
    paid: true,
    field: 'Business',
    deadline: '2026-03-25',
    description: 'Coca-Cola internship across marketing, supply chain, and innovation.',
    majors: ['Business', 'Engineering', 'Marketing'],
    tags: ['consumer-goods', 'paid'],
    url: 'https://www.coca-colacompany.com/careers',
    stipend: '$8,300/month',
    duration: '12 weeks'
  },
  {
    title: 'Summer Internship',
    company: 'Walmart',
    location: { city: 'Bentonville', state: 'AR' },
    type: 'summer',
    paid: true,
    field: 'Business',
    deadline: '2026-03-15',
    description: 'Walmart internship in retail operations, supply chain, and technology.',
    majors: ['Business', 'Computer Science', 'Engineering'],
    tags: ['retail', 'paid'],
    url: 'https://careers.walmart.com',
    stipend: '$8,000/month',
    duration: '12 weeks'
  },
  {
    title: 'Internship Program',
    company: 'Target',
    location: { city: 'Minneapolis', state: 'MN' },
    type: 'summer',
    paid: true,
    field: 'Business',
    deadline: '2026-03-22',
    description: 'Target internship in merchandising, supply chain, and technology.',
    majors: ['Business', 'Computer Science', 'Engineering'],
    tags: ['retail', 'paid'],
    url: 'https://careers.target.com',
    stipend: '$7,800/month',
    duration: '12 weeks'
  },
  {
    title: 'Internship Program',
    company: 'Amazon Retail',
    location: { city: 'Seattle', state: 'WA' },
    type: 'summer',
    paid: true,
    field: 'Business',
    deadline: '2026-03-20',
    description: 'Amazon retail and operations internship.',
    majors: ['Business', 'Engineering', 'Computer Science'],
    tags: ['retail', 'paid'],
    url: 'https://www.amazon.jobs/internships',
    stipend: '$8,200/month',
    duration: '12 weeks'
  },

  // ─── ENERGY & UTILITIES (ADDITIONAL) ────────────────────────
  {
    title: 'Engineering Internship',
    company: 'Chevron',
    location: { city: 'San Ramon', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Engineering',
    deadline: '2026-03-25',
    description: 'Chevron petroleum engineering and operations internship.',
    majors: ['Petroleum Engineering', 'Mechanical Engineering'],
    tags: ['energy', 'oil-gas', 'paid'],
    url: 'https://www.chevron.com/careers',
    stipend: '$8,500/month',
    duration: '12 weeks'
  },
  {
    title: 'Summer Internship',
    company: 'ExxonMobil',
    location: { city: 'Houston', state: 'TX' },
    type: 'summer',
    paid: true,
    field: 'Engineering',
    deadline: '2026-03-28',
    description: 'ExxonMobil engineering and operations internship.',
    majors: ['Petroleum Engineering', 'Mechanical Engineering', 'Electrical Engineering'],
    tags: ['energy', 'oil-gas', 'paid'],
    url: 'https://www.exxonmobil.com/careers',
    stipend: '$8,700/month',
    duration: '12 weeks'
  },
  {
    title: 'Engineering Internship',
    company: 'Shell',
    location: { city: 'Houston', state: 'TX' },
    type: 'summer',
    paid: true,
    field: 'Engineering',
    deadline: '2026-03-30',
    description: 'Shell internship in petroleum and renewable energy engineering.',
    majors: ['Petroleum Engineering', 'Mechanical Engineering'],
    tags: ['energy', 'oil-gas', 'paid'],
    url: 'https://www.shell.com/careers',
    stipend: '$8,400/month',
    duration: '12 weeks'
  },

  // ─── NONPROFITS & SOCIAL IMPACT ────────────────────────────
  {
    title: 'Internship Program',
    company: 'American Red Cross',
    location: { city: 'Washington', state: 'DC' },
    type: 'summer',
    paid: false,
    field: 'Law & Government',
    deadline: '2026-04-01',
    description: 'Red Cross internship in disaster relief and public health.',
    majors: ['Public Health', 'Social Work', 'Business'],
    tags: ['nonprofit', 'humanitarian', 'unpaid'],
    url: 'https://www.redcross.org/careers',
    stipend: null,
    duration: '10 weeks'
  },
  {
    title: 'Fellowship Program',
    company: 'Teach for America',
    location: { city: 'New York', state: 'NY' },
    type: 'summer',
    paid: true,
    field: 'Education',
    deadline: '2026-02-28',
    description: 'Teach for America internship placing students in underserved schools.',
    majors: ['Education', 'Business', 'STEM'],
    tags: ['nonprofit', 'education', 'paid'],
    url: 'https://www.teachforamerica.org',
    stipend: '$5,500/month',
    duration: '6-8 weeks'
  },
  {
    title: 'Internship',
    company: 'Human Rights Watch',
    location: { city: 'New York', state: 'NY' },
    type: 'summer',
    paid: false,
    field: 'Law & Government',
    deadline: '2026-03-10',
    description: 'Human Rights Watch internship in research and advocacy.',
    majors: ['International Relations', 'Law', 'Political Science'],
    tags: ['nonprofit', 'advocacy', 'unpaid'],
    url: 'https://www.hrw.org/careers',
    stipend: null,
    duration: '10 weeks'
  },

  // ─── RESEARCH INSTITUTIONS (ADDITIONAL) ───────────────────
  {
    title: 'Summer Researcher',
    company: 'Princeton University IAS',
    location: { city: 'Princeton', state: 'NJ' },
    type: 'summer',
    paid: true,
    field: 'Science',
    deadline: '2026-02-15',
    description: 'Institute for Advanced Study research position.',
    majors: ['Physics', 'Mathematics', 'Computer Science'],
    tags: ['research', 'paid', 'academic', 'competitive'],
    url: 'https://www.ias.edu',
    stipend: '$7,000/month',
    duration: '10 weeks'
  },
  {
    title: 'Internship Program',
    company: 'Caltech JPL',
    location: { city: 'Pasadena', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Science',
    deadline: '2026-03-01',
    description: 'JPL internship in aerospace engineering and space research.',
    majors: ['Aerospace Engineering', 'Physics', 'Computer Science'],
    tags: ['research', 'space', 'paid', 'government'],
    url: 'https://www.jpl.nasa.gov/',
    stipend: '$7,800/month',
    duration: '10 weeks'
  },
  {
    title: 'Summer Fellowship',
    company: 'Lawrence Berkeley Lab',
    location: { city: 'Berkeley', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Science',
    deadline: '2026-02-20',
    description: 'Lawrence Berkeley Lab research internship in physics and engineering.',
    majors: ['Physics', 'Engineering', 'Computer Science'],
    tags: ['research', 'paid', 'government'],
    url: 'https://www.lbl.gov/',
    stipend: '$6,800/month',
    duration: '10 weeks'
  },
  {
    title: 'Summer Internship',
    company: 'Oak Ridge National Laboratory',
    location: { city: 'Oak Ridge', state: 'TN' },
    type: 'summer',
    paid: true,
    field: 'Science',
    deadline: '2026-02-25',
    description: 'ORNL internship in energy science and engineering.',
    majors: ['Physics', 'Engineering', 'Chemistry'],
    tags: ['research', 'paid', 'government'],
    url: 'https://www.ornl.gov/',
    stipend: '$6,600/month',
    duration: '10 weeks'
  },

  // ─── ADDITIONAL TECH & STARTUP ──────────────────────────────
  {
    title: 'Software Engineering Internship',
    company: 'Grammarly',
    location: { city: 'San Francisco', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-04-05',
    description: 'Grammarly internship in NLP and web development.',
    majors: ['Computer Science', 'Software Engineering', 'Linguistics'],
    tags: ['tech', 'nlp', 'paid'],
    url: 'https://www.grammarly.com/careers',
    stipend: '$8,000/month',
    duration: '12 weeks'
  },
  {
    title: 'Engineering Internship',
    company: 'Duolingo',
    location: { city: 'Pittsburgh', state: 'PA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-04-10',
    description: 'Duolingo engineering internship in language learning platform.',
    majors: ['Computer Science', 'Software Engineering'],
    tags: ['tech', 'education', 'paid'],
    url: 'https://www.duolingo.com/careers',
    stipend: '$8,100/month',
    duration: '12 weeks'
  },
  {
    title: 'Engineering Internship',
    company: 'DuckDuckGo',
    location: { city: 'Paoli', state: 'PA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-04-08',
    description: 'DuckDuckGo search engine and privacy internship.',
    majors: ['Computer Science', 'Software Engineering'],
    tags: ['tech', 'privacy', 'paid'],
    url: 'https://duckduckgo.com/careers',
    stipend: '$7,800/month',
    duration: '12 weeks'
  },
  {
    title: 'Engineering Internship',
    company: 'GitLab',
    location: { city: 'San Francisco', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-04-12',
    description: 'GitLab engineering internship in DevOps and collaboration tools.',
    majors: ['Computer Science', 'Software Engineering'],
    tags: ['tech', 'devops', 'remote', 'paid'],
    url: 'https://about.gitlab.com/careers',
    stipend: '$7,900/month',
    duration: '12 weeks'
  },
  {
    title: 'Software Engineering Internship',
    company: 'Twitch',
    location: { city: 'San Francisco', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-04-05',
    description: 'Twitch engineering internship in live streaming platform.',
    majors: ['Computer Science', 'Software Engineering'],
    tags: ['tech', 'streaming', 'paid'],
    url: 'https://www.twitch.tv/jobs',
    stipend: '$8,200/month',
    duration: '12 weeks'
  },
  {
    title: 'Product Management Internship',
    company: 'Asana',
    location: { city: 'San Francisco', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-04-10',
    description: 'Asana product and engineering internship.',
    majors: ['Computer Science', 'Business'],
    tags: ['tech', 'product', 'paid'],
    url: 'https://asana.com/careers',
    stipend: '$8,000/month',
    duration: '12 weeks'
  },
  {
    title: 'Engineering Internship',
    company: 'Airtable',
    location: { city: 'San Francisco', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-04-08',
    description: 'Airtable engineering internship in database and collaboration.',
    majors: ['Computer Science', 'Software Engineering'],
    tags: ['tech', 'database', 'paid'],
    url: 'https://airtable.com/careers',
    stipend: '$8,000/month',
    duration: '12 weeks'
  },

  // ─── MANUFACTURING & INDUSTRIAL ────────────────────────────
  {
    title: 'Engineering Internship',
    company: '3M',
    location: { city: 'St. Paul', state: 'MN' },
    type: 'summer',
    paid: true,
    field: 'Engineering',
    deadline: '2026-03-20',
    description: '3M internship in material science and product engineering.',
    majors: ['Chemical Engineering', 'Materials Science', 'Mechanical Engineering'],
    tags: ['manufacturing', 'paid'],
    url: 'https://www.3m.com/3M/en_US/careers/',
    stipend: '$7,800/month',
    duration: '12 weeks'
  },
  {
    title: 'Engineering Internship',
    company: 'Honeywell',
    location: { city: 'Charlotte', state: 'NC' },
    type: 'summer',
    paid: true,
    field: 'Engineering',
    deadline: '2026-03-25',
    description: 'Honeywell internship in aerospace, building, and industrial solutions.',
    majors: ['Aerospace Engineering', 'Electrical Engineering', 'Mechanical Engineering'],
    tags: ['manufacturing', 'paid'],
    url: 'https://www.honeywell.com/us/en/careers',
    stipend: '$8,000/month',
    duration: '12 weeks'
  },
  {
    title: 'Summer Internship',
    company: 'Parker Hannifin',
    location: { city: 'Cleveland', state: 'OH' },
    type: 'summer',
    paid: true,
    field: 'Engineering',
    deadline: '2026-03-28',
    description: 'Parker Hannifin motion and control technology internship.',
    majors: ['Mechanical Engineering', 'Electrical Engineering'],
    tags: ['manufacturing', 'paid'],
    url: 'https://www.parker.com/careers',
    stipend: '$7,600/month',
    duration: '12 weeks'
  },
  {
    title: 'Engineering Internship',
    company: 'ABB',
    location: { city: 'Cary', state: 'NC' },
    type: 'summer',
    paid: true,
    field: 'Engineering',
    deadline: '2026-03-30',
    description: 'ABB internship in power and automation technology.',
    majors: ['Electrical Engineering', 'Mechanical Engineering'],
    tags: ['manufacturing', 'paid'],
    url: 'https://new.abb.com/careers',
    stipend: '$7,700/month',
    duration: '12 weeks'
  },

  // ─── TELECOMMUNICATIONS ────────────────────────────────────
  {
    title: 'Engineering Internship',
    company: 'Verizon',
    location: { city: 'New York', state: 'NY' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-03-28',
    description: 'Verizon network engineering and technology internship.',
    majors: ['Electrical Engineering', 'Computer Science'],
    tags: ['telecom', 'paid'],
    url: 'https://www.verizon.com/careers',
    stipend: '$7,900/month',
    duration: '12 weeks'
  },
  {
    title: 'Summer Internship',
    company: 'AT&T',
    location: { city: 'Dallas', state: 'TX' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-03-25',
    description: 'AT&T network and technology internship.',
    majors: ['Electrical Engineering', 'Computer Science'],
    tags: ['telecom', 'paid'],
    url: 'https://www.att.com/careers',
    stipend: '$7,800/month',
    duration: '12 weeks'
  },
  {
    title: 'Internship Program',
    company: 'T-Mobile',
    location: { city: 'Bellevue', state: 'WA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-04-01',
    description: 'T-Mobile network and software engineering internship.',
    majors: ['Electrical Engineering', 'Computer Science'],
    tags: ['telecom', 'paid'],
    url: 'https://www.t-mobile.com/careers',
    stipend: '$7,700/month',
    duration: '12 weeks'
  },

  // ─── MEDIA & COMMUNICATIONS (ADDITIONAL) ───────────────────
  {
    title: 'Media Internship',
    company: 'CNN',
    location: { city: 'Atlanta', state: 'GA' },
    type: 'summer',
    paid: false,
    field: 'Arts & Media',
    deadline: '2026-03-20',
    description: 'CNN news internship in journalism and production.',
    majors: ['Journalism', 'Media Studies', 'Communications'],
    tags: ['media', 'news', 'unpaid'],
    url: 'https://www.cnn.com/careers',
    stipend: null,
    duration: '10 weeks'
  },
  {
    title: 'Editorial Internship',
    company: 'The New York Times',
    location: { city: 'New York', state: 'NY' },
    type: 'summer',
    paid: true,
    field: 'Arts & Media',
    deadline: '2026-02-28',
    description: 'New York Times journalism and editorial internship.',
    majors: ['Journalism', 'Communications', 'English'],
    tags: ['media', 'news', 'paid', 'competitive'],
    url: 'https://www.nytimes.com/careers',
    stipend: '$8,000/month',
    duration: '12 weeks'
  },
  {
    title: 'Journalism Internship',
    company: 'The Washington Post',
    location: { city: 'Washington', state: 'DC' },
    type: 'summer',
    paid: true,
    field: 'Arts & Media',
    deadline: '2026-03-01',
    description: 'Washington Post journalism internship.',
    majors: ['Journalism', 'Communications', 'English'],
    tags: ['media', 'news', 'paid'],
    url: 'https://www.washingtonpost.com/careers',
    stipend: '$7,800/month',
    duration: '12 weeks'
  },
  {
    title: 'Production Internship',
    company: 'BBC',
    location: { city: 'London', state: 'UK' },
    type: 'summer',
    paid: false,
    field: 'Arts & Media',
    deadline: '2026-03-15',
    description: 'BBC production and journalism internship.',
    majors: ['Media Studies', 'Film', 'Journalism'],
    tags: ['media', 'international', 'unpaid'],
    url: 'https://www.bbc.com/careers',
    stipend: null,
    duration: '10 weeks'
  },

  // ─── FASHION & LUXURY GOODS ────────────────────────────────
  {
    title: 'Fashion Internship',
    company: 'LVMH',
    location: { city: 'Paris', state: 'France' },
    type: 'summer',
    paid: true,
    field: 'Business',
    deadline: '2026-03-10',
    description: 'LVMH luxury goods and fashion internship.',
    majors: ['Business', 'Fashion', 'Marketing'],
    tags: ['fashion', 'international', 'paid'],
    url: 'https://www.lvmh.com/careers',
    stipend: '$6,500/month',
    duration: '12 weeks'
  },
  {
    title: 'Design Internship',
    company: 'Nike',
    location: { city: 'Beaverton', state: 'OR' },
    type: 'summer',
    paid: true,
    field: 'Arts & Media',
    deadline: '2026-03-25',
    description: 'Nike design and product development internship.',
    majors: ['Design', 'Business', 'Engineering'],
    tags: ['sports', 'design', 'paid'],
    url: 'https://www.nike.com/careers',
    stipend: '$8,000/month',
    duration: '12 weeks'
  },
  {
    title: 'Internship Program',
    company: 'Adidas',
    location: { city: 'Boston', state: 'MA' },
    type: 'summer',
    paid: true,
    field: 'Business',
    deadline: '2026-03-28',
    description: 'Adidas design and business internship.',
    majors: ['Design', 'Business', 'Engineering'],
    tags: ['sports', 'paid'],
    url: 'https://www.adidas.com/careers',
    stipend: '$7,800/month',
    duration: '12 weeks'
  },

  // ─── ADDITIONAL FINANCIAL SERVICES ─────────────────────────
  {
    title: 'Trading Internship',
    company: 'Optiver',
    location: { city: 'Chicago', state: 'IL' },
    type: 'summer',
    paid: true,
    field: 'Business',
    deadline: '2026-02-20',
    description: 'Optiver algorithmic trading internship.',
    majors: ['Computer Science', 'Mathematics', 'Physics', 'Finance'],
    tags: ['finance', 'trading', 'paid', 'competitive'],
    url: 'https://www.optiver.com/careers',
    stipend: '$13,000/month',
    duration: '10 weeks'
  },
  {
    title: 'Quantitative Internship',
    company: 'Jane Street',
    location: { city: 'New York', state: 'NY' },
    type: 'summer',
    paid: true,
    field: 'Business',
    deadline: '2026-02-15',
    description: 'Jane Street quantitative trading internship.',
    majors: ['Computer Science', 'Mathematics', 'Physics'],
    tags: ['finance', 'trading', 'quant', 'paid', 'competitive'],
    url: 'https://www.janestreet.com/careers',
    stipend: '$14,000/month',
    duration: '10 weeks'
  },
  {
    title: 'Internship Program',
    company: 'Goldman Sachs (Technology)',
    location: { city: 'New York', state: 'NY' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-03-15',
    description: 'Goldman Sachs engineering internship in financial technology.',
    majors: ['Computer Science', 'Engineering'],
    tags: ['finance', 'tech', 'paid'],
    url: 'https://www.goldmansachs.com/careers/students/',
    stipend: '$9,000/month',
    duration: '12 weeks'
  },

  // ─── EDUCATION & ONLINE LEARNING ───────────────────────────
  {
    title: 'Engineering Internship',
    company: 'Coursera',
    location: { city: 'Mountain View', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-04-08',
    description: 'Coursera engineering internship in online education platform.',
    majors: ['Computer Science', 'Software Engineering'],
    tags: ['education', 'tech', 'paid'],
    url: 'https://www.coursera.org/careers',
    stipend: '$8,000/month',
    duration: '12 weeks'
  },
  {
    title: 'Product Internship',
    company: 'Udemy',
    location: { city: 'San Francisco', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-04-10',
    description: 'Udemy product and engineering internship.',
    majors: ['Computer Science', 'Business'],
    tags: ['education', 'tech', 'paid'],
    url: 'https://www.udemy.com/careers',
    stipend: '$7,900/month',
    duration: '12 weeks'
  },
  {
    title: 'Engineering Internship',
    company: 'Khan Academy',
    location: { city: 'Mountain View', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-04-05',
    description: 'Khan Academy engineering internship in educational technology.',
    majors: ['Computer Science', 'Software Engineering'],
    tags: ['education', 'nonprofit', 'paid'],
    url: 'https://www.khanacademy.org/careers',
    stipend: '$7,800/month',
    duration: '12 weeks'
  },

  // ─── REAL ESTATE & PROPERTY TECH ────────────────────────────
  {
    title: 'Technology Internship',
    company: 'Zillow',
    location: { city: 'Seattle', state: 'WA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-04-05',
    description: 'Zillow engineering internship in real estate technology.',
    majors: ['Computer Science', 'Software Engineering', 'Data Science'],
    tags: ['tech', 'real-estate', 'paid'],
    url: 'https://www.zillow.com/careers',
    stipend: '$8,100/month',
    duration: '12 weeks'
  },
  {
    title: 'Engineering Internship',
    company: 'Redfin',
    location: { city: 'Seattle', state: 'WA' },
    type: 'summer',
    paid: true,
    field: 'Technology',
    deadline: '2026-04-08',
    description: 'Redfin technology internship in real estate disruption.',
    majors: ['Computer Science', 'Software Engineering'],
    tags: ['tech', 'real-estate', 'paid'],
    url: 'https://www.redfin.com/careers',
    stipend: '$8,000/month',
    duration: '12 weeks'
  },

  // ─── TRANSPORTATION & LOGISTICS ────────────────────────────
  {
    title: 'Engineering Internship',
    company: 'UPS',
    location: { city: 'Atlanta', state: 'GA' },
    type: 'summer',
    paid: true,
    field: 'Engineering',
    deadline: '2026-03-20',
    description: 'UPS supply chain and operations engineering internship.',
    majors: ['Industrial Engineering', 'Mechanical Engineering', 'Computer Science'],
    tags: ['logistics', 'paid'],
    url: 'https://www.ups.com/careers',
    stipend: '$7,700/month',
    duration: '12 weeks'
  },
  {
    title: 'Internship Program',
    company: 'FedEx',
    location: { city: 'Memphis', state: 'TN' },
    type: 'summer',
    paid: true,
    field: 'Business',
    deadline: '2026-03-25',
    description: 'FedEx logistics and operations management internship.',
    majors: ['Business', 'Engineering', 'Computer Science'],
    tags: ['logistics', 'paid'],
    url: 'https://www.fedex.com/careers',
    stipend: '$7,600/month',
    duration: '12 weeks'
  },

  // ─── HEALTHCARE ADDITIONAL ────────────────────────────────
  {
    title: 'Clinical Internship',
    company: 'Cleveland Clinic',
    location: { city: 'Cleveland', state: 'OH' },
    type: 'summer',
    paid: false,
    field: 'Healthcare',
    deadline: '2026-04-01',
    description: 'Cleveland Clinic clinical research internship.',
    majors: ['Medicine', 'Biology', 'Health Sciences'],
    tags: ['healthcare', 'research', 'unpaid'],
    url: 'https://www.clevelandclinic.org/careers',
    stipend: null,
    duration: '10 weeks'
  },
  {
    title: 'Research Internship',
    company: 'Johns Hopkins',
    location: { city: 'Baltimore', state: 'MD' },
    type: 'summer',
    paid: true,
    field: 'Healthcare',
    deadline: '2026-04-05',
    description: 'Johns Hopkins biomedical research internship.',
    majors: ['Biology', 'Chemistry', 'Medicine'],
    tags: ['healthcare', 'research', 'paid'],
    url: 'https://www.jhm.edu/careers',
    stipend: '$7,500/month',
    duration: '10 weeks'
  },
  {
    title: 'Clinical Internship',
    company: 'Stanford Medicine',
    location: { city: 'Stanford', state: 'CA' },
    type: 'summer',
    paid: true,
    field: 'Healthcare',
    deadline: '2026-04-10',
    description: 'Stanford medical research internship.',
    majors: ['Medicine', 'Biology', 'Chemistry'],
    tags: ['healthcare', 'research', 'paid'],
    url: 'https://www.stanford.edu/careers',
    stipend: '$7,800/month',
    duration: '10 weeks'
  },

  // ─── GOVERNMENT ADDITIONAL ────────────────────────────────
  {
    title: 'Internship',
    company: 'FBI',
    location: { city: 'Washington', state: 'DC' },
    type: 'summer',
    paid: true,
    field: 'Law & Government',
    deadline: '2026-03-01',
    description: 'FBI internship in law enforcement and cybersecurity.',
    majors: ['Criminal Justice', 'Computer Science', 'Engineering'],
    tags: ['government', 'security', 'paid', 'clearance'],
    url: 'https://www.fbi.gov/careers',
    stipend: '$7,200/month',
    duration: '10 weeks'
  },
  {
    title: 'Internship Program',
    company: 'Bureau of Labor Statistics',
    location: { city: 'Washington', state: 'DC' },
    type: 'summer',
    paid: true,
    field: 'Science',
    deadline: '2026-03-10',
    description: 'BLS internship in statistics and economic data.',
    majors: ['Statistics', 'Economics', 'Mathematics'],
    tags: ['government', 'research', 'paid'],
    url: 'https://www.bls.gov/careers',
    stipend: '$6,800/month',
    duration: '10 weeks'
  },
  {
    title: 'Internship',
    company: 'Census Bureau',
    location: { city: 'Suitland', state: 'MD' },
    type: 'summer',
    paid: true,
    field: 'Science',
    deadline: '2026-03-15',
    description: 'Census Bureau internship in data science and demography.',
    majors: ['Statistics', 'Computer Science', 'Demography'],
    tags: ['government', 'research', 'paid'],
    url: 'https://www.census.gov/careers',
    stipend: '$6,900/month',
    duration: '10 weeks'
  },
];

// ────────────────────────────────────────────────────────────────────
// SCRAPER EXECUTION
// ────────────────────────────────────────────────────────────────────

export async function scrapeInternships() {
  try {
    log(SCRAPER_NAME, 'Starting internships data scraper...', 'progress');

    // Deduplicate + validate through the central data-integrity module
    const { validateAndDedup } = await import('../../services/data-integrity.js');

    // Also load existing data to preserve verified entries that aren't in the scraper
    let existingVerified = [];
    try {
      const { promises: fsPromises } = await import('fs');
      const { join: joinPath, dirname: dirnamePath } = await import('path');
      const { fileURLToPath: fileURL } = await import('url');
      const existingPath = joinPath(dirnamePath(fileURL(import.meta.url)), '..', '..', 'data', 'scraped', 'internships.json');
      const existing = JSON.parse(await fsPromises.readFile(existingPath, 'utf-8'));
      existingVerified = (existing.internships || []).filter(e => e._verified);
      log(SCRAPER_NAME, `Preserving ${existingVerified.length} verified entries from existing data`, 'progress');
    } catch { /* File might not exist yet */ }

    // Verified entries first so they win dedup conflicts
    const allEntries = [...existingVerified, ...INTERNSHIPS_DATA];
    const { clean: deduplicated, stats } = validateAndDedup('internships', allEntries);

    log(SCRAPER_NAME, `Curated ${deduplicated.length} unique internship programs (${stats.duplicatesRemoved} dupes removed, ${stats.verified} verified preserved)`, 'progress');

    // Build metadata
    const metadata = {
      lastScraped: new Date().toISOString().slice(0, 10),
      totalCount: deduplicated.length,
      sources: [
        'Company career portals (Google, Microsoft, Amazon, Meta, Apple, etc.)',
        'Government agencies (NASA, NIH, EPA, CDC, NSF, DoE)',
        'Financial institutions (Goldman Sachs, JPMorgan, etc.)',
        'Research institutions (NSF REU programs, DOE SULI, National Labs)',
        'Media and entertainment (Disney, Netflix, etc.)',
        'Engineering firms (Boeing, SpaceX, Tesla, etc.)',
        'Consulting firms (McKinsey, BCG, Bain, Deloitte, PwC, EY, KPMG)',
      ]
    };

    const output = {
      metadata,
      internships: deduplicated
    };

    // Save to disk
    const filePath = await saveScrapedData('internships.json', output);
    log(SCRAPER_NAME, `Successfully saved ${deduplicated.length} internships`, 'success');

    return {
      success: true,
      count: deduplicated.length,
      filePath
    };
  } catch (err) {
    log(SCRAPER_NAME, `Error: ${err.message}`, 'error');
    throw err;
  }
}
